<?php

namespace app\index\controller;

use think\Controller;
use think\Request;
use think\Db;
class Base extends  Controller
{
    protected  $request ='';

    protected $dataform = 'users';

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->request = Request::instance();
    }


    public function checkToken($token,$users)
    {
        $res = Db::name($this->dataform)->field('timeout')->where(['name'=>$users,'token'=>$token])->find();

        if (!empty($res)) {
            if (time() - $res['timeout'] > 0) {
                return json(['code'=>103,'msg'=>'token過期，請重新登入']);
            }

            $new_time_out = time() + 604800; //604800是七天
            $res = Db::name($this->dataform)
                ->where(['name'=>$users,'token'=>$token])
                ->update(['timeout' => $new_time_out]);

            if ($res) {
                return json(['code'=>101,'msg'=>'登入成功']); //token验证成功
            }
        }

        return json(['code'=>102,'msg'=>'token錯誤，請重新登入']); //token错误验证失败
    }


}