<?php

namespace app\index\controller;

use think\Controller;
use think\Request;
use think\Db;
use think\Session;
class Base extends  Controller
{
    protected  $request ='';

    protected  $dataform = 'users';

    protected  $common = 'url';

    protected  $other  = 'other';


    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->request = Request::instance();
        $urls  = Db::name($this->common)->order('id desc')->find();
        $other = Db::name($this->other)->order('id desc')->find();
        $login_img = Db::name('login_img')->order('id desc')->find();
        $type_img = Db::name('type_img')->order('id desc')->find();
        $shi_img = Db::name('shi_img')->order('id desc')->find();
        $this->assign('urls',$urls);
        $this->assign('other',$other);
        $this->assign('login_img',$login_img);
        $this->assign('type_img',$type_img);
        $this->assign('shi_img',$shi_img);
    }


    public function check_user(){
        if(Session::get('member')){
            return true;
        }else{
            return false;
        }
    }






    //todo 注释
    public function checkToken($token,$users)
    {
        $res = Db::name($this->dataform)->field('timeout')->where(['name'=>$users,'token'=>$token])->find();

        if (!empty($res)) {
            if (time() - $res['timeout'] > 0) {
                return json(['code'=>103,'msg'=>'token過期，請重新登入']);
            }

            $new_time_out = time() + 604800; //604800是七天
            $res = Db::name($this->dataform)
                ->where(['name'=>$users,'token'=>$token])
                ->update(['timeout' => $new_time_out]);

            if ($res) {
                return json(['code'=>101,'msg'=>'登入成功']); //token验证成功
            }
        }

        return json(['code'=>102,'msg'=>'token錯誤，請重新登入']); //token错误验证失败
    }


}