<?php

namespace app\index\controller;

use think\Controller;
use think\Request;
use think\Db;
class Home extends  Controller
{
    protected  $request ='';

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->request = Request::instance();
    }

    


}