<?php
namespace  app\index\controller;

use app\index\controller\Base;
use think\Db;

class Index  extends  Base {


    protected $play = 'play_cates';

    protected $order = 'order';

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub

        if($this->check_user() == false){
            return $this->redirect('login/login');
        }
    }


    //1 选择页面
    public  function index(){
         if($this->request->isGet()){
             $cates = Db::name($this->play)->order('id desc')->select();
             $this->assign('cates',$cates);
             return $this->fetch();
         }

         if($this->request->isPost()){
            $cid = input('post.cid','','int');
            $mid = input('post.mid','','int');

            if(empty($cid) || empty($mid)|| !isset($mid)){
                return false;
            }

            $res = Db::name($this->order)->insertGetId(['cid'=>$cid,'mid'=>$mid,'orderId'=>makeOrder()]);

            if($res){
                return json(['code'=>200,'msg'=>'操作成功','order'=>$res]);
            }else{
                return json(['code'=>400,'msg'=>'網路故障，請重新操作']);
            }
         }
    }

    //充值方式
    public function types(){
        if($this->request->isGet()){
            return $this->fetch();
        }

        if($this->request->isPost()){
            $order = input('post.order','','int');
            $pid   = input('post.pid','','int');

            if(empty($pid) || empty($order)|| $order <=0 || !isset($order)){
                return false;
            }

            $res = Db::name($this->order)->where('id',$order)->update(['pid'=>$pid]);

            if($res){
                return json(['code'=>200,'pid'=>$pid]);
            }else{
                return json(['code'=>400,'msg'=>'操作失败']);
            }

        }
    }

    //type1:好友转账
    public function info(){
        if($this->request->isGet()){
            return $this->fetch();
        }

        if($this->request->isPost()){

        }

    }

    //type2:充值模板
    public function chong(){
        if($this->request->isGet()){
            return $this->fetch();
        }

        if($this->request->isPost()){

        }
    }

    //type3:转速快
    public function zhuan(){
        if($this->request->isGet()){
            return $this->fetch();
        }

        if($this->request->isPost()){

        }
    }


}