<?php
namespace  app\index\controller;

use app\index\controller\Base;
use think\Db;

class News  extends  Base {


    protected $table = 'news';

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub

        if($this->check_user() == false){
            return $this->redirect('login/login');
        }
    }


    public function index(){
        $info = Db::name($this->table)->order('id desc')->find();
        $this->assign('info',$info);
        return $this->fetch();
    }


}