<?php
namespace  app\index\controller;

use app\index\controller\Base;
use think\Db;

class News  extends  Base {

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub

        if($this->check_user() == false){
            return $this->redirect('login/login');
        }
    }


    public function index(){

        return $this->fetch();
    }


}